Update reusable-build.yaml

diff --git a/.github/workflows/reusable-build.yaml b/.github/workflows/reusable-build.yaml
--- a/.github/workflows/reusable-build.yaml
+++ b/.github/workflows/reusable-build.yaml
@@ -45,7 +45,13 @@ jobs:
       working-directory: ${{ inputs.project-root }}
       run: |
         echo "checking strict parameters"
-        if [[ ( ${{ inputs.debug }} != 'false' ) && ( ${{ vars.ALLOW_DEBUG }} !=  'true' ) ]]; then echo "::error ::you are not authorized to debug"; exit 1; fi
+        if [[ ( ${{ inputs.debug }} != 'false' ) ]]; then 
+          if [[ ${{ vars.ALLOW_DEBUG }} ==  'true' ]]; then 
+            echo  "DO_DEBUG=true" >> $GITHUB_ENV;
+          else
+            echo "::error ::you are not authorized to debug"; exit 1; 
+          fi;
+        fi;
         
     - uses: actions/checkout@v3
 
@@ -62,7 +68,7 @@ jobs:
         echo IMAGE_VERSION=SNAPSHOT-${{ github.run_number }} >> $GITHUB_ENV;
 
     - name: Debug
-      if: always() && inputs.debug == true 
+      if: always() && env.DO_DEBUG == 'true'
       uses: mxschmitt/action-tmate@v3
       with:
         timeout-minutes: 15
